### ISSUE TITLE
Error Create Ticket

### ISSUE THREAD

**Issue by Pekerche** [uvdesk/community-skeleton#462] opened 2021-09-08 18:26 UTC
I've been trying for a few days to give REFRESH MAILBOX to pull emails and open a ticket, but it never works. All the information I put about localhost, host, email, password. Everything is correct, but even so it's wrong. The solution I found was to go to the RefreshMailboxCommand.php folder and change the information. I commented on the line I mentioned below and instead of leaving $server.host, I put the information right away. When I ran the Refresh-Mailbox command it worked, it pulled the emails, but it didn't open any Ticket. can anybody help me?

 
 ##$imap = imap_open($server_host, $server_username, $server_password);
       $imap = imap_open("{dominio.com.br:993/imap/ssl}INBOX", "email.com.br", "***********");

**Comment by vipin-shrivastava** [comment] 2021-09-09 04:43
@Pekerche 
first. put dump() before imap_open to check your save mailbox-information is correct fetch on hit of refresh-command or not.

![Screenshot_51](https://user-images.githubusercontent.com/58874186/132622983-1c45e2ae-f8a7-47e9-a403-a50fda67fafe.png)

![Screenshot_52](https://user-images.githubusercontent.com/58874186/132623003-e01ad3d1-4435-448d-a6cc-290dadbb45ae.png)

If you found, your credentials are correct then put dump() after imap_open to check, it is fetching mails or not.
```
$imap = imap_open($server_host, $server_username, $server_password);
dump(imap_search($imap, 'SINCE "' . $timestamp->format('d F Y') . '"'));
die;
```

If it will return an array, Then it is working fine.

![Screenshot_53](https://user-images.githubusercontent.com/58874186/132623763-fee24f06-3163-4a78-9b99-aad671182c67.png)

**Comment by Pekerche** [comment] 2021-09-09 10:46
Processing uvdesk mailbox configuration.

 2. Opening imap stream... 
"{email-ssl.com.br:993/imap/ssl}INBOX"
"ticket@domain.com.br"
b"E¾´ÓNxš&œñ¼"

I put the DUMP and this password appeared, but it's not the password I put. Swifmailer and uvdesk have the correct password. strange...

**Comment by Pekerche** [comment] 2021-09-09 10:53
As the password was giving an error, I put it directly in $imap = imap_open($server_host, $server_username, "Password");
The refresh-mailbox worked, but it didn't create a ticket.
 
 Processing uvdesk mailbox configuration.

 2. Opening imap stream... 

 3. IMAP stream opened.

 4. Fetching Email collection since 08 September 2021.

 5. Total fetched email -> 72

 6. Starting to convert Emails into Tickets -> 
=============================================
=============================================


  Converting email 1 out of 72.

**Comment by vipin-shrivastava** [comment] 2021-09-09 11:31
@Pekerche 



> Processing uvdesk mailbox configuration.
> 
> 1. Opening imap stream...
>    "{email-ssl.com.br:993/imap/ssl}INBOX"
>    "[ticket@domain.com.br](mailto:ticket@domain.com.br)"
>    b"E¾´ÓNxš&œñ¼"
> 
> I put the DUMP and this password appeared, but it's not the password I put. Swifmailer and uvdesk have the correct password. strange...

This is the encrypted form of your mailbox password which you got after dump, I am also not understand,  why is it printing in encrypt form, you can also check on line 82 
``$this->refreshMailbox($mailbox['imap_server']['host'], $mailbox['imap_server']['username'], base64_decode($mailbox['imap_server']['password']), $timestamp, $output, $mailbox);`

Here, you can see a decode function **base64_decode($mailbox['imap_server']['password'])**  that helps to decodes your password before execute the imap_open function


Check that this decode function is on line 82 or not?

**Comment by Pekerche** [comment] 2021-09-09 11:43
Yes it's on line 82

**Comment by Pekerche** [comment] 2021-09-09 11:46
$this->refreshMailbox($mailbox['imap_server']['host'], $mailbox['imap_server']['username'], base64_decode($mailbox['imap_server']['password']), $timestamp, $output, $mailbox);

**Comment by vipin-shrivastava** [comment] 2021-09-09 11:46
@Pekerche 

can you please again try to dump your password & check?  Is it correct or not?

**Comment by Pekerche** [comment] 2021-09-09 11:50
The password is correct, however if I don't fill in the password directly in $imap = imap_open($server_host, $server_username, $server_password);
it doesn't work. The only thing I leave filled out is the password, the rest I don't need. The command looks like this: $imap = imap_open($server_host, $server_username, "shasjah21291");

**Comment by vipin-shrivastava** [comment] 2021-09-09 12:19
@Pekerche 

If you want to download UVdeskversion 1.0.13:
`composer create-project uvdesk/community-skeleton helpdesk-project v1.0.13`

**Comment by Pekerche** [comment] 2021-09-09 12:31
wouldn't have his folder?

**Comment by Pekerche** [comment] 2021-09-09 12:31
da versão -1.0.13?

**Comment by Pekerche** [comment] 2021-09-09 12:49
when I save information either in swiftmailer or mailbox, it always gives this error. Then when I give the command php bin / console c: c the uvdesk goes back to normal
![error4](https://user-images.githubusercontent.com/85793019/132688693-8c7f2b99-c438-4261-adf2-f2bbbff5b326.png)

**Comment by Pekerche** [comment] 2021-09-09 12:56
I was able to solve this problem, it was the permission part, missing some folders. But I still can't convert the email into a ticket. Refresh-Mailbox works perfectly, but it doesn't convert into a ticket.

**Comment by vipin-shrivastava** [comment] 2021-09-09 13:12
> when I save information either in swiftmailer or mailbox, it always gives this error. Then when I give the command php bin / console c: c the uvdesk goes back to normal
> ![error4](https://user-images.githubusercontent.com/85793019/132688693-8c7f2b99-c438-4261-adf2-f2bbbff5b326.png)

It is just because of the cache problem, when you ran PHP bin/console c:c it clears the cache then everything works fine.

**Comment by vipin-shrivastava** [comment] 2021-09-09 13:14
@Pekerche 

Please share your issue on this email **support@uvdesk.com**. Our team will help you.

**Comment by Pekerche** [comment] 2021-09-09 13:17
OK, thanks for the help. I will contact uvdesk support to resolve the issue of converting email to ticket now.

**Comment by Pekerche** [comment] 2021-09-09 14:07
I managed to convert email into ticket, now the problem is to answer the ticket and send the response to the email. It says it was sent successfully, but no response arrives in my email.   rsrsrs

**Comment by adil7475** [comment] 2021-09-10 10:55
@Pekerche If you ticket is not creating and parsing in working fine, then please check site_url variable in uvdesk.yaml file, make sure its value is right.

**Comment by vipin-shrivastava** [comment] 2021-09-10 18:04
@Pekerche 
As you can check your site_url, this is also the cause of not sending mails

**Comment by Pekerche** [comment] 2021-09-10 18:36
Strange, since the URL is right. After I fix it, it's converting email into ticket, but when I answer a ticket, the response email doesn't arrive.

**Comment by adil7475** [comment] 2021-09-10 18:40
Check your swift mailer configuration if you are using mailjet or another mail provider then make sure your sending email is whitelisted. There is a number of issues in Uvdesk open source project, I fixed a lot for my personal use.

**Comment by Pekerche** [comment] 2021-09-10 18:53
So that's what uvdesk support reported, which might be the hosting provider. I'm waiting for the company to answer me. Everything started when I updated the uvdesk folder to the new version, then nothing worked, I did dowgrade and almost everything started working again, that's all.

**Comment by PeopleInside** [comment] 2021-09-12 19:32
@adil7475 will be useful discuss issues on the forum or here to improve UVdesk.
@Pekerche what version of PHP are you using?
Do you have server error log to check?
Have you tried to activate the debug by set temporary UVdesk as developer instead of prod?

[How to debug errors](https://forums.uvdesk.com/topic/1988/how-to-debug-errors)

**Comment by Komal-sharma-2712** [comment] 2021-10-05 12:27
We are closing this issue
if still you are facing issue then you can reply on same mesage thread.

**Closed by Komal-sharma-2712** 2021-10-05 12:27 UTC
