### ISSUE TITLE
Agent activity list xhr request 500 internal server error Notice: Undefined index: after

### ISSUE THREAD

**Issue by tamer-hassan** [uvdesk/community-skeleton#441] opened 2021-08-22 14:36 UTC
Dear,

Fresh install and upon clicking agent activity list, it loads forever, and in inspector, the xhr request shows 500 internal server error, with symfony page about "Notice: Undefined index: after"

This is a bit strange given the XHR request URL contains both after and before query parameters

Screenshot below
![image](https://user-images.githubusercontent.com/512891/130359083-40262920-e752-4c76-8a29-9a82eb79a59b.png)

**Comment by Sanjaybhattwebkul** [comment] 2021-08-23 12:35
@tamer-hassan 

This issue is fix in our **new release V1.0.16**

![List-Agent](https://user-images.githubusercontent.com/86394952/130447743-a4c02ba1-032d-439d-a2bd-9e34e331ca20.png)
 **![Agent-Activity](https://user-images.githubusercontent.com/86394952/130447737-69c9627f-edf7-49fc-b639-94984ce185b1.png)**

**Comment by Sanjaybhattwebkul** [comment] 2021-08-25 05:52
@tamer-hassan 

Have you checked this issue with the new release V1.0.16, If you are getting this issue again then let me know

**Comment by yasdevops** [comment] 2021-08-28 06:44
@Sanjaybhattwebkul 

Upgraded to v1.0.16 but the issue still exists

![image](https://user-images.githubusercontent.com/46381003/131209158-1d138b87-0013-4824-9701-867ab8899922.png)

**Comment by tamer-hassan** [comment] 2021-08-28 06:48
@Sanjaybhattwebkul 

Upgraded to v1.0.16 but the issue still occurs (even after hard refresh)
Notice the line number of the error exception is now different after the upgrade, but the same error.

![image](https://user-images.githubusercontent.com/512891/131209232-5bf40c9a-4105-4189-90c5-231ca90f5b2f.png)

**Comment by vipin-shrivastava** [comment] 2021-08-29 07:16
@tamer-hassan 
As I checked with V1.0.16. Agent activity is working fine.
I also added a screenshot here.
![Screenshot_4](https://user-images.githubusercontent.com/58874186/131242017-6056483c-c290-479c-80bf-ff92c3d0fbd1.png)

Run **cache clear command** => `Php bin/console c:c`

After running the cache clear command then check again. If you still getting the same issue please let me know.

**Comment by tamer-hassan** [comment] 2021-08-29 08:19
@vipin-shrivastava 

I already have done that as part of the update instructions... Nevertheless, I ran the cache clear command again

```
# php bin/console c:c

 // Clearing the cache for the dev environment with debug true                                                          
                                                           
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared. 
```

But still getting the same error as in the last screenshot above.

By the way, in case it matters, this is a fresh install and there's no agent activity yet.

**Comment by tamer-hassan** [comment] 2021-08-29 08:32
Update: I edited the .env file in the root of the project, and changed:
`APP_ENV=dev`
to:
`APP_ENV=prod`

The issue then doesn't happen.

**Comment by vipin-shrivastava** [comment] 2021-08-30 05:35
@tamer-hassan 

In `APP_ENV=prod` mode It will not show any error to you. If you want to know about the error use `APP_ENV=dev`  mode.

**Comment by tamer-hassan** [comment] 2021-08-30 07:04
@vipin-shrivastava default fresh install .env file contained APP_ENV=dev
I guess this was the problem

**Comment by vipin-shrivastava** [comment] 2021-08-30 10:07
@tamer-hassan 
Are you still getting the 500 internal server error?

No, That's not the problem. Actually, fresh uvdesk is always set to development mode in the .env file.

**Comment by tamer-hassan** [comment] 2021-08-30 10:33
yes, in dev mode I still get the 500 internal server error with Notice: undefined index: after

**Comment by vipin-shrivastava** [comment] 2021-08-30 10:56
@tamer-hassan 
Please follow the below steps :
1. Download the zip from [here](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip).
2. After downloading the project (zip) extract it.
3. Now, Go to the `**uvdesk-community-v1.0.16->vendor->uvdesk** ` folder location.
4. Here, you have to copy two folders **Core-framework** & **support-center-bundle**.
5. After copy from here, Paste it in your project file location `**your_project_name->vendor->uvdesk** `  first delete these two only from here then paste it.

Now, you issue is resolved. If you still getting the same issue please let me know

**Comment by tamer-hassan** [comment] 2021-08-30 13:15
Tried what you suggested, but same issue, as what you described doesn't change anything since I followed the upgrade instructions in the forum to the T and already had the latest core-framework and support-center-bundle with composer update.
https://forums.uvdesk.com/topic/1833/how-to-upgrade-uvdesk

I also re-ran `php bin/console c:c` after doing what you suggested, but same error.

![image](https://user-images.githubusercontent.com/512891/131344588-dd4fa287-6e42-41ad-9102-f08148cc5cdf.png)

**Comment by vipin-shrivastava** [comment] 2021-08-30 13:28
@tamer-hassan 

Are you copy the **core framework & support-center-bundle** folder from the downloaded & paste it into your project?

If you have done, Please run the following command in sequential order 
```
php bin/console d:c:clear-metadata
php bin/console d:s:u --force --dump-sql --complete
php bin/console c:c  
php bin/console c:c --env prod
```

Hope this will work  for you

**Comment by tamer-hassan** [comment] 2021-08-30 16:06
no , that doesn't help either

**Comment by vipin-shrivastava** [comment] 2021-08-30 16:13
@tamer-hassan 

Mail your issue on Support@webkul.com. Our support team member will help you .

**Comment by PeopleInside** [comment] 2021-09-12 20:50
Hi @tamer-hassan , the issue still persist?
I'm unable to replicate with PHP 7.4, what is your PHP version?

The issue is present also if you set UVdesk to prod mode and clean cache?
Have you tried to check logs?
[How to debug errors](https://forums.uvdesk.com/topic/1988/how-to-debug-errors)

**Comment by vipin-shrivastava** [comment] 2021-10-01 15:28
@tamer-hassan 
are you still facing the same issue? Any update?

**Comment by Komal-sharma-2712** [comment] 2021-10-05 07:21
There is no updates from your side so we are closing this issue.
If still facing the same issue please let us know.

**Closed by Komal-sharma-2712** 2021-10-05 07:21 UTC

**Comment by tamer-hassan** [comment] 2021-11-22 08:12
Updated to v1.0.18 and issue still exists
PHP 7.4.3 if that is worth noting

**Comment by vipin-shrivastava** [comment] 2021-11-22 08:19
@tamer-hassan 
 
Can you please share the screenshot again & also tell us what issues are you facing after updating in v1.0.18?

**Comment by tamer-hassan** [comment] 2021-11-22 08:23
Issue is the same as titled in the issue here, when clicking "Agent Activity", the page loads forever, and the XHR request gives 500 internal server error with the "Notice: Undefined index: after"

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/512891/142827260-b37eda5e-face-4c14-82cd-63e3e2be0596.png">

from var/log/dev.log

`[2021-11-22T09:17:28.688041+01:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: Undefined index: after" at /var/www/support/vendor/uvdesk/core-framework/Controller/Report.php line 70 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: after at /var/www/support/vendor/uvdesk/core-framework/Controller/Report.php:70)"} []`

**Comment by vipin-shrivastava** [comment] 2021-11-22 08:24
@tamer-hassan 
After updating to v1.0.18, Please run the below command & then check again : 
```
PHP bin/console d:s:u --force
PHP bin/console c:c
```
If you still facing the same issue please let us know.

**Comment by tamer-hassan** [comment] 2021-11-22 08:27
```
# php bin/console d:s:u --force

 Updating database schema...

     4 queries were executed
                                                                                                                        
 [OK] Database schema updated successfully!

# php bin/console c:c

 // Clearing the cache for the dev environment with debug true                                                          

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.
```

Still facing the same issue!

**Comment by vipin-shrivastava** [comment] 2021-11-22 09:53
@tamer-hassan 

Mail your helpdesk URL with admin login credentials on Support@uvdesk.com. Our support team members will help you.

**Comment by tamer-hassan** [comment] 2021-11-23 04:16
I did contact support@uvdesk.com ... they did the same thing I did and mentioned here before as a workaround (changing APP_ENV to "prod" instead of "dev" in the .env file) 😄 and told me the issue is solved.

**Comment by vipin-shrivastava** [comment] 2021-11-23 04:58
@tamer-hassan 

Have you checked on dev mode? are you still getting the same issue?

**Comment by tamer-hassan** [comment] 2021-11-23 05:25
apologies.. switched it back to dev mode, cleared cache, and it is indeed working..
