### ISSUE TITLE
Emails sent to mailbox alias not imported as tickets

### ISSUE THREAD

**Issue by Ataraxxia** [uvdesk/community-skeleton#555] opened 2022-04-04 18:11 UTC
# Bug report

### Emails sent to mailbox alias not properly imported
My current setup uses mailbox with unfriendly name to emphasize it's not user mailbox `virtual-uvdesk@example.com` and I use an alias as a friendly name `helpdesk@example.com`. The import script recognizes emails sent to `helpdesk` but they do not appear as tickets, only emails sent to `virtual-uvdesk@example.com` are properly imported.

I am using version 1.0.18

The following is an output for an email sent to alias, we can see the script can detect it.
```bash
root@uvdesk:/var/www/uvdesk# sudo -u www-data php /var/www/uvdesk/bin/console uvdesk:refresh-mailbox virt-uvdesk@example.com

 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

 3. IMAP stream opened.

 4. Fetching Email collection since 03 April 2022.

 5. Total fetched email -> 1

 6. Starting to convert Emails into Tickets ->
=============================================
=============================================


  Converting email 1 out of 1.

 Mailbox refreshed successfully !!!
```

Is this a bug or possibly a missing feature?

**Comment by vipin-shrivastava** [comment] 2022-04-05 04:55
@Ataraxxia 

Thanks for reporting, we will check & fix it soon.

**Comment by fiftyz** [comment] 2022-04-14 19:43
Duplicate of uvdesk/mailbox-component#85. 
The mailbox-component is responsable for creating tickets from emails so I think this issue should be continued there.

**Comment by Komal-sharma-2712** [comment] 2022-06-17 13:14
We are closing this issue because this issue is a duplicate check it [here.](https://github.com/uvdesk/mailbox-component/issues/85)

So we continued there in the mailbox-component.

**Closed by Komal-sharma-2712** 2022-06-17 13:14 UTC
