### ISSUE TITLE
SMTP Issue for custom domain 

### ISSUE THREAD

**Issue by Aman1kr** [uvdesk/community-skeleton#577] opened 2022-07-06 13:38 UTC
Hello Uvdesk Team,

I have been trying my best to setup STMP for custom domain, I updated the Swift mailer credentials and completed the mail box setup but i am unable to receive any kind of mail from the system.

Kindly look over the concern issue.

Thank You
Aman Kumar

**Comment by Komal-sharma-2712** [comment] 2022-07-07 06:25
@Aman1kr 

As we have checked your ticket id: **378096** and your helpdesk, you have added a condition in the **Ticket Created workflow** which was the cause of not sending emails to your customers. 
Now, we have updated the workflow for you, and now your helpdesk is working fine.

If you have any other queries, let us know.

**Comment by Komal-sharma-2712** [comment] 2022-07-08 08:17
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.

**Closed by Komal-sharma-2712** 2022-07-08 08:17 UTC
