### ISSUE TITLE
Open uvdesk with root folder

### ISSUE THREAD

**Issue by codefreak558** [uvdesk/community-skeleton#588] opened 2022-08-03 18:20 UTC
**Description**  
What I am looking to do is open the support page without typing /public into the url

**Example**  
https://support.example.com/public to https://support.example.com

**Comment by vipin-shrivastava** [comment] 2022-08-04 11:54
@codefreak558 

you have to create the symbolic link for that project, Follow the given blog: https://www.freecodecamp.org/news/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link/

**Comment by codefreak558** [comment] 2022-08-04 12:05
So I would make a symbolic link from the `/public` folder to the `/` folder correct

**Comment by Komal-sharma-2712** [comment] 2022-09-02 09:25
@codefreak558 

Your issue is resolved now or not?
If the issue is still let us know.

**Comment by codefreak558** [comment] 2022-09-11 10:42
No still not.

**Comment by Komal-sharma-2712** [comment] 2022-09-12 04:51
If you still facing the same issue then mail us at [support@uvdesk.com](mailto:support@uvdesk.com) with your query and screenshot of the errors. Our team will help you.

**Comment by Komal-sharma-2712** [comment] 2022-10-03 09:47
We are not getting any reply or ticket from your side so we are closing this issue. If you have any queries so reply in the same thread or mail us at [support@uvdesk.com](mailto:support@uvdesk.com)

**Closed by Komal-sharma-2712** 2022-10-03 09:47 UTC
