### ISSUE TITLE
Email replies cause new ticket thread

### ISSUE THREAD

**Issue by steveb85** [uvdesk/community-skeleton#397] opened 2021-04-30 21:09 UTC
# Bug report

every email reply creates a new ticket rather than adding to the thread. Apart from this the system is working, and i can’t see any errors, In the symfony dash there is no “emails” in that section but not sure if that’s applicable. All emails are sending and receiving fine, just the new thread thing that is annoying. Ticket links work. 

Latest version of UV desk
Php 7.2 

All other prerequisites as required. Nothing else on this server. 

    1. Ticket created via email    
    2. Agent replies from within UVdesk
    3. User replies, new ticket thread is created
### Expected result

**Comment by PeopleInside** [comment] 2021-05-01 08:39
I'm testing and while I'm testing found other issues.
PHP 7.4 UvDesk version V -1.0.13

I opened a ticket from the web interface than replied to the email that alert me a ticket has been created.
o i tested the situation where user get the email of the opening ticket and want add information than reply to this email.

The user reply are flagged as read on email inbox but reply are not added to the ticket.
If this kind of issue persist means ticket are not updated I need find another ticket solution... I don't tolerate ticket are not opened or updated correctly because I can miss important reports / requests.

Strange because... I believe to had tested this scenario when ticket system was updated to the latest version and was not able to reproduce.

I still need test the scenario of replies that open a new ticket, I will do now.

OK @steveb85 I done this test:
- I opened a ticket from the web interface
- As user received the ticket email open email, if I reply to this email the reply is not added anywhere in the ticket system. This is bad and must be fixed!
- From the ticket system I see the open ticket also operator has been emailed about the open ticket. I made a reply from the ticket system operator side
- User received the reply email
- Replied to the ticket reply email and the reply was correctly added to the ticket

I'm unable to reproduce the issue you are describing but let's wait UVdesk team.

**Comment by PeopleInside** [comment] 2021-05-01 08:58
I suppose the reason for have this issue can be two:

- Are you sure the agent reply email has the right ticket number, in the right format, in the email subject?
- Maybe your php file for manage ticket is different from mine, can be updated before mine so maybe the issue you are facing is caused by some update.. in this case UVdesk team need assist you

**Comment by steveb85** [comment] 2021-05-01 12:47
@PeopleInside can you confirm with me the subject format your replies sent with? Both from the agent and the customer?

**Comment by PeopleInside** [comment] 2021-05-01 13:32
**Reply To The Customer's ticket**
Subject: [ #{% ticket.id %} ] [ {%ticket.subject%} ] New reply

This is the subject I have in the email template for the email customer get when operator reply to the customer ticket.
If user reply to this ticket without editing the subject I get reply.

I'm using MailBird, maybe I need test if I'm able to see no issue even if I reply directly from the Gmail interface but I think things should not change.

**Comment by PeopleInside** [comment] 2021-05-01 13:44
I tested from Gmail and all works fine.
I created a ticket by sending an email from Gmail.
Replied to the opening email alert and also generate a test reply from the operator once the ticket was create in UVdesk.

Replied to the operator reply and all replies was added in the ticket after the cronjob

**Comment by vipin-shrivastava** [comment] 2021-05-03 06:14
@steveb85 

UVdesk : v1.0.13
Php : v7.4

I also tested  : 

1> User created ticket by mail 
2> admin replied on that ticket from web interface
3> Customer replied on the same ticket by mail 

It is adding all the replied in thread by User on that ticket .
you can see screenshot [here](https://prnt.sc/12ey6yi) .

**Comment by steveb85** [comment] 2021-05-03 16:22
So i just set up a Gmail account, and when a ticket is created or replied from Gmail, that works as expected. There is something that is causing the problem when I use my @mac.com email account, as the customer, then every reply because a new ticket and the thread is all over the place.

**Comment by steveb85** [comment] 2021-05-03 16:23
It doesn’t seem to matter if it’s from the web app or an email client the @mac.com accounts cause this problem. Perhaps something that can be patched?

**Comment by steveb85** [comment] 2021-05-03 16:26
The same problem is happening with my business email address, which is an outlook account, with our own domain. At least we see that the gmail is working, so there is something perhaps in how the headers or subject is formatted ?

**Comment by PeopleInside** [comment] 2021-05-03 16:46
@steveb85 I'M testing with my domain and with a free Hotmail account.

_While I wait the test results I wanna suggest: when you need add information to your latest message here, please use edit instead of write another message and so generate other email notifications._

Results:

I'm unable to replicate with customer email using my domain email address and unable to replicate from a free hotmail account used as customer.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/116905930-ec299f80-ac3f-11eb-9652-663a3b8e5d2a.jpg)

**Comment by steveb85** [comment] 2021-05-03 16:51
@PeopleInside sorry about the comments, fixed now. 

Yes i see that Hotmail works, same as yahoo and gmail., but @mac. Is common in the music industry which is our space, and seems to cause a problem, perhaps you can share your URL, and I can try generating a ticket from my email there, and just test the results. It seems to also happen with my office365 email address.

**Comment by PeopleInside** [comment] 2021-05-03 16:57
Sure you can try here: https://helpdesk.peopleinside.it/en/
This is not a test instance but the HelpDesk I use for my personal website. You can try to open a ticket here.

**Comment by PeopleInside** [comment] 2021-05-03 17:14
Confirmed, the issue is present. For that we need help from @papnoisanjeev 
Maybe @steveb85 should open a ticket in your test UVdesk @papnoisanjeev so you can check the duoble ticket and also check email headers. I don't know if you want suggest to try open a ticket and test the issue at uvdesk.com ticket system.

Let us know, in my server email from mac.com domain never add replies to the existent ticket but always open a new ticket.

Thank you.

**Comment by steveb85** [comment] 2021-05-03 17:15
Thanks @PeopleInside much appreciate the help.

**Comment by PeopleInside** [comment] 2021-05-03 17:16
You are welcome, let's wait an update here from the developer that has been mentioned.
Thank you for reporting this issue.

**Comment by papnoisanjeev** [comment] 2021-05-04 03:51
@PeopleInside  The issue may be due to some different header or content in this specific case.

@Himaniwebkul  please collect mails for the same from @PeopleInside so that we can check row content of mails for headers and other information.

@vipin-shrivastava  Check the issue for this case get the emails for the same from @Himaniwebkul

**Comment by PeopleInside** [comment] 2021-05-04 08:38
If you need mac.com email please ask to @steveb85 , I deleted all email received for the rest and I don't forward in any case without uthorization. As I don't have anymore you can ask to the user that have a mac.com address. Thank you

**Comment by papnoisanjeev** [comment] 2021-05-10 08:04
@steveb85 

We have asked for the emails on ticket but still didn't got any reply from your side.
Please provide it so that we can fix it.

**Comment by steveb85** [comment] 2021-05-10 13:52
That is a different email address, I'll start a ticket from the email address giving problems now. Apologies for missing that email, it's not my main account.

**Comment by steveb85** [comment] 2021-05-11 23:37
I wrote a ticket, and your support staff closed it already before any replies. Please re-open or request a new thread

**Comment by PeopleInside** [comment] 2021-05-12 03:18
> I wrote a ticket, and your support staff closed it already before any replies. Please re-open or request a new thread

Strange, can you share the ticked ID so the UVdesk team can find easly the interested ticket? Thank you

**Comment by papnoisanjeev** [comment] 2021-05-12 04:37
@steveb85 

As we have checked your ticket and it seems like a test ticket.
so somebody from our team closed it as it was looking like a test ticket.

Check this: https://prnt.sc/12tvfrk

Now ticket is again in open status and you can start your conversation with content we have asked to you.
We will assign it to somebody from our team and will look into it.

**Comment by steveb85** [comment] 2021-05-19 13:43
@papnoisanjeev still waiting for feedback after opening a few more tickets with you

**Comment by PeopleInside** [comment] 2021-05-21 11:19
Any news @papnoisanjeev  about that?

**Comment by vipin-shrivastava** [comment] 2021-05-21 11:34
@PeopleInside  @steveb85 

Our team did not have any **@mac** account  but recently we create a **@mac** account so now we will test this & fix this as soon as possible.

**Comment by vipin-shrivastava** [comment] 2021-05-24 16:58
@PeopleInside  @steveb85 

As we found the **@mac.com** email address has officially been  [phased out](https://prnt.sc/13cubqg). So our team create an account with the **@icloud.com** domain and checked the issue but we didn't found any issue.
It is working fine & also the reply added in the same ticket thread.

I added the screenshots here :
1. https://prnt.sc/13cul85 .
2. https://prnt.sc/13cunuo .
3. https://prnt.sc/13cus5i .
4. https://prnt.sc/13cpx94 .
5. https://prnt.sc/13cpt2y .

I think the issue is with your domain as we check with **@icloud** mail service . it is working fine.

**Comment by PeopleInside** [comment] 2021-05-24 17:35
Umh.. @vipin-shrivastava what happen if @steveb85 open a ticket in UVdesk at https://www.uvdesk.com/en/ and what happen if you reply to the ticket and the user reply to you from a mac domain?

In this case you should be able to get email headers and understand why for the mac.com domain ticket are create as new.
If this happen maybe in the UVdesk code something is not property work or you have to explain why this happen.

You cannot create mac.com email address but you can test the situation with the help of @steveb85

**Comment by steveb85** [comment] 2021-05-25 00:11
> Umh.. @vipin-shrivastava what happen if @steveb85 open a ticket in UVdesk at https://www.uvdesk.com/en/ and what happen if you reply to the ticket and the user reply to you from a mac domain?
> 
I'd be happy to help with this, I think it would be worthwhile.

**Comment by vipin-shrivastava** [comment] 2021-05-25 10:30
@steveb85 

As I have replied to you on the ticket. please provide all the needful things & information related.

**Comment by steveb85** [comment] 2021-05-28 19:44
@vipin-shrivastava did you get my reply?

**Comment by vipin-shrivastava** [comment] 2021-05-31 10:49
@steveb85  
Yes, I got your reply and this time it is working perfectly , As your reply  has added in the same thread .

can you please tell me? which mail box service had you used to send reply mail this time?

**Comment by PeopleInside** [comment] 2021-06-10 19:47
@steveb85  waiting your feedback.
@vipin-shrivastava you should be able to understand that or you need improve the ticket system to show such info. You can check in mailbox.

In UVdesk is not easy understand from customer email address and to email address because this info are not fully showed.
Should ve more easy understand the email of the customer, you can see in customer panel.

**Comment by steveb85** [comment] 2021-06-11 17:36
I still use iCloud .Mac service with that email, it hasn’t changed since 2002, it still seems unstable with Mac but works with outlook gmail and most of the customers we have.

**Comment by vipin-shrivastava** [comment] 2021-07-30 06:05
@steveb85 

is this issue still there ? As I tested with Icloud, I didn't get any new ticket and it also added the new reply in the same ticket thread.

**Comment by steveb85** [comment] 2021-07-30 18:31
yes this is still here, i just tried again, including with a reply from my browser and a reply from my mail app. both had the same result, new ticket created.

**Comment by steveb85** [comment] 2021-07-30 18:32
I am running 1.1.13 haven’t upgraded, has that caused a fix?

**Comment by vipin-shrivastava** [comment] 2021-07-31 00:20
@steveb85 

Yes, first you upgrade your opensource uvdesk & then try as I tested this with lastest uvdesk.

If you still get the same issue, please let us know.

**Comment by steveb85** [comment] 2021-08-02 15:15
@vipin-shrivastava I’m having a lot of trouble on the upgrade. My menu has changed with the new features, but if i click on reports, nothing happens. Down the bottom of my console it still says 1.1.13 not 1.1.14 I’ve been through all the composer updates but not sure what is happening. I have been getting the error In Cache.php line 99: file_put_contents(/root/.composer/cache/repo/https—-files.symfony.com/): failed to open stream : Is a directory i can’t find support on that anywhere.

**Comment by steveb85** [comment] 2021-08-02 16:26
thanks @PeopleInside that worked. now all functionality is working, however weirdly down the bottom of my member/dashboard it still says 1.0.13 not .14! however, I can access reports and new features. and this is a fresh install. and the CHANGELOG file has the .14 items in it. perhaps this is just an oversight? I did replace the few yaml files frm my original install along with the public folder, as it was mentioned in one of the forums to do that to save your old preferences. testing the email reply’s now

**Comment by steveb85** [comment] 2021-08-02 16:31
@PeopleInside @vipin-shrivastava i can confirm that with the update, this problem is still happening. new thread for each reply to the email. no solution found yet.

**Comment by vipin-shrivastava** [comment] 2021-08-02 20:08
@steveb85 
As I tested Last time, it was not creating new ticket.
I will checked it again & inform you.

Thanks for your patience 

If you found any issues, please let us know

**Comment by steveb85** [comment] 2021-08-02 20:09
any idea why it would show 1.1.13 on the bottom of my dashboard? could that be the issue? odd from a new install from the zip of the latest stable.

**Comment by vipin-shrivastava** [comment] 2021-08-02 20:13
@steveb85 
No, it's not an issue. Actually we had forgotten to update the version in the bottom bar.

**Comment by PeopleInside** [comment] 2021-08-02 20:29
> 
> 
> @steveb85
> As I tested Last time, it was not creating new ticket.
> I will checked it again & inform you.
> 
> Thanks for your patience
> 
> If you found any issues, please let us know

The issue is not maybe with icloud but with @mac.com

**Comment by vipin-shrivastava** [comment] 2021-08-03 15:04
@steveb85 @PeopleInside 

As I tested with @icloud.com. It is not creating any new tickets. I also tried to create a test mail account @mac.com but unfortunately, Apple does not provide mail ID with @mac.com. If you can provide us a test account. It will be easy for us.

**Comment by PeopleInside** [comment] 2021-08-03 15:58
@vipin-shrivastava and @steveb85 

@mac.com email address cannot be anymore created but users with this email address exist and is the case opened by @steveb85.

Since the start of this issue I can understand that UVdesk team and me will be not able to send mail from a @mac.com email address.

Maybe for resolve the diagnosis @steveb85 can create a test UVdesk instance or can create an admin operator and give access to the UVdesk team by contacting UVdesk team by ticket https://www.uvdesk.com/en/contact/

Than @steveb85 can send an email from @mac.com to his support email address. Maybe UVdesk team need have access to this support email address or email receved by @mac.com should be saved with .eml format and attached to ticket https://www.uvdesk.com/en/contact/ so the UVdesk team can check.

The best scenario would be create a completely separated UVdesk test instance and create a test support email and give full FTP access to the UVdesk team of the folder where UVdesk is installed, full access to the test support email than simply create a ticket sending an email from @mac.com, reply to ticket.. create the issue so UVdesk team will be able to check.

**Comment by papnoisanjeev** [comment] 2021-08-21 13:34
@steveb85 

Please try to do as suggested by @PeopleInside  to create a test instance for @mac.com
so that we can look into this.

**Closed by papnoisanjeev** 2021-08-21 13:34 UTC
Labels: help wanted

**Comment by PeopleInside** [comment] 2021-08-30 18:26
@steveb85 you will shotly get a private email for me, let's see if we are able to create the scenario for UVdesk to resolve this as I saw the issue on my server thanks to you. I will try to keep this issue updated

**Comment by PeopleInside** [comment] 2021-08-30 18:55
@steveb85 sorry, you will not get my email for now, I get errors while I'm trying to install a test instance.
I will see if I can do in some other way, if I'm able to install a clean UVdesk install, if so you will get an email when I will be ready.

Issue: https://github.com/uvdesk/community-skeleton/issues/453

**Comment by PeopleInside** [comment] 2021-08-31 16:20
Great now the work in on the UVdesk team.
For UVdesk team the ticket with all necessary information for do diagnostic on the issue is #25572

I created an instance steveb85 has created a ticket and created also a reply so the duplicate ticket is now visible.
UVdesk team can also check email headers as I give all necessary access to diagnose and resolve.
Thank you.

**Comment by PeopleInside** [comment] 2021-09-13 21:57
@steveb85  thank you for all emails and the patience.
My ticket with the UVdesk team still be opened (Ticket #25572) so we are working to try to do the best.
I had some server issue but now all is up and is working since some day and I informed the team about your updates in the test ticket system.

Let's see if will be possible catch the cause.

**Comment by PeopleInside** [comment] 2021-09-27 12:00
## Issue resolved

Hi Stephen,
the issue with mac.com and UVdesk should be resolved right now.

Seems you never reply to my latest ticket created for you but your latest reply was correctly added to the test ticket and today I received a notification from the UVdesk team that confirm latest patch fix the issue.

You need take a full folder and backup of UVdesk than you can download 
support-center-boundle
core-framework
on your PC.
Than you can unzip the content and replace this two folders in your uvdeskfolder/vendor/uvdesk/

Note: when you unzip the two folders the name of this two folders will be followed by the master world. if you want drag and drop using FTP you may need remove master world from the end of the file name or simply open the folder and transfer all content inside to the relative folder on your server.

When you done and replaced this two folders content in your server you will need clean cache with the SSH command: php bin/console c:c

**Comment by steveb85** [comment] 2021-09-27 13:08
mate ! this is great, thanks so much for leading the charge, i’m impressed they fixed it so quickly,. i just sent a test ticket, and will try it and then going to set some time aside tonight to update my system, thanks again mate


Stephen Bartlett
+1 646 824 8145
***@***.***
www.stephenbartlettmusic.com

**Comment by steveb85** [comment] 2021-09-27 14:33
FYI i sent an email to create a ticket and nothing was generated, perhaps check the cron job is working?


Stephen Bartlett
+1 646 824 8145
***@***.***
www.stephenbartlettmusic.com

**Comment by PeopleInside** [comment] 2021-09-27 14:34
Hi Steve, I can see your ticket is number 21. 
Please check better your email. Check also in the spam and let me know if you get the notification in the spam.

**Comment by PeopleInside** [comment] 2021-09-27 14:55
I see, the testing instance is not working. Email are not sent to the customer but to another email address.
I'm checking why and will try to update you.

**Comment by PeopleInside** [comment] 2021-09-27 15:40
## Issue is not resolved, the UVdesk team seems is not right.
I am able to see issue still persist: duplicate ticket created when a reply from mac.com address is received and elaborated.
I'm sorry.

**Comment by vipin-shrivastava** [comment] 2021-12-09 04:50
@steveb85 

We have added some fixes for this case.
Please make the below updates on your project and check it if working fine for you!

Locate a path in your project.
vendor/uvdesk under uvdesk folder you will see some folders.

Delete core-framework and mailbox-component folder.

Then again clone both using the below command at the same place (under vendor/uvdesk folder).

git clone https://github.com/uvdesk/core-framework
git clone https://github.com/uvdesk/mailbox-component

Finally, clear your cache and make a try !!

**Comment by steveb85** [comment] 2021-12-09 14:38
@vipin-shrivastava Hi i did the update successfully, however, now I’m getting an error on the imap_open, [“exception” => ErrorException] 

this wasn’t happening before, could this be something from the update? without being able to refresh the mailbox (manually or through cron) i can’t test the results.

**Comment by PeopleInside** [comment] 2021-12-09 14:55
Hi @steveb85,
I'm glad to see you updated UVdesk.

Please be sure to go in your UVdesk Dashboard than save all email settings again inserting one by one password of each email address.

New update can introduce email password encryption so maybe you are getting an error because of the email password issue.
I hope after saving again all email settings (SwiftMailer and MailBox) your issue will be resolved.

**Comment by steveb85** [comment] 2021-12-09 15:06
hey @PeopleInside thanks, i deleted emails, and cleared cache again and it seems to be working. I’ll do some testing of the .mac emails later tonight
thanks again all.

**Comment by PeopleInside** [comment] 2021-12-09 15:15
I'm hapy to read that your UVdesk instance is now working @steveb85 .
My thanks is to you to report such important issue and to the UVdesk team that worked to fix this very well.

**Comment by steveb85** [comment] 2021-12-09 15:22
@PeopleInside @vipin-shrivastava it looks to have worked! i’ve tested a few times and everything is going great! congrats tot he team on solving this one! A big step for us all.

**Comment by regberink** [comment] 2021-12-09 22:38
I have the same issue also after updating.

Workflow -> when status changed send email.
Email will not set Referenceid nor Reply-to in the header. so it will break. <- Reply fails and creates new ticket.

Workflow -> when agent reply 
Email will be send with the referenceid <- reply is succesfull

**Comment by PeopleInside** [comment] 2021-12-09 22:44
Hi @regberink,
for this let's wait developers.

@vipin-shrivastava

**Comment by regberink** [comment] 2021-12-09 22:50
@PeopleInside 
@vipin-shrivastava 

I am testing all kinds of methods everything related to a new thread(reply/create) is working fine. everythings else (change status, change priority) or whatever trigger i set. i will not add the reference id or reply-to. in the header. so it will never check back as a reply to in the system because you are checking those 2 entries. against the database if i am correct?

**Comment by regberink** [comment] 2021-12-09 23:02
Ok here's the fix:

core-framework/workflow/actions/Ticket/MailCustomer.php 

Add line $headers = ['References' => $entity->getReferenceIds()]; on line 72
Change Line 95 
$message = $container->get('email.service')->sendMail($subject, $message, $entity->getCustomer()->getEmail());
to:
$message = $container->get('email.service')->sendMail($subject, $message, $entity->getCustomer()->getEmail(),$headers);

Now its working

**Comment by regberink** [comment] 2021-12-09 23:24
This will fix all emails related to MailCustomer when replying.

some nicer code:

**Change** 
} else {
                    $message = $container->get('email.service')->sendMail($subject, $message, $entity->getCustomer()->getEmail(),$headers);
                }
**To:**

} else {
                     if (!empty($entity->getReferenceIds())) {
                        $headers = ['References' => $entity->getReferenceIds()];
                     }
                    $message = $container->get('email.service')->sendMail($subject, $message, $entity->getCustomer()->getEmail(),$headers);
                }

**Comment by papnoisanjeev** [comment] 2021-12-10 04:36
@regberink 

Please create a pull request for the suggested changes if everything works well we we merge it with main repository of project
And you will also become a contributor for project as well.

**Comment by PeopleInside** [comment] 2021-12-10 10:44
I never yet tested this. I'm trying to save the edit on my repo and maybe now I see I create a pull request.
The code need to be tested and reviewed. Feel free to open a new pull request if mine is not right or want create one with your profile.

**Comment by regberink** [comment] 2021-12-10 10:47
i have never done a pull request all is fine by me if you do it. 
but this one is nicer if you would like to change the code:

} else {
$message = $container->get('email.service')->sendMail($subject, $message, $entity->getCustomer()->getEmail(),$headers);
}
To:

} else {
if (!empty($entity->getReferenceIds())) {
$headers = ['References' => $entity->getReferenceIds()];
}
$message = $container->get('email.service')->sendMail($subject, $message, $entity->getCustomer()->getEmail(),$headers);
}

**Comment by PeopleInside** [comment] 2021-12-10 10:49
In my pull request I done also this changes.
Just need check if my pull request is fine, the UVdesk team will check it :)

Thanks for this!

**Comment by vipin-shrivastava** [comment] 2021-12-10 13:10
@PeopleInside 

We will check & If everything works fine then we will merge it.

@PeopleInside @regberink Thanks, for your contribution.
