### ISSUE TITLE
Selective ticket generation SSMTP via php

### ISSUE THREAD

**Issue by steveb85** [uvdesk/community-skeleton#531] opened 2022-02-23 19:40 UTC
# Bug report

### Title
I have a php form that sends an email based up user input inside my application. The email is sent and received by the mailbox associated with UVdesk. Uvdesk, sees it when manually using RefreshMailbox, and prints no error, and the counter is correct, however no new ticket is generated. If i send an email manually between the two mailboxes, it works, however the PHP ssmtp generated email, while it’s received is not turned into a ticket. 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. 1.0.18

**Comment by Komal-sharma-2712** [comment] 2022-02-24 12:44
@steveb85 

As I have checked, I am not able to reproduce this issue.
Can you please share some screenshots so that will be easy for me?

Which version of PHP are you using?

**Comment by PeopleInside** [comment] 2022-02-24 22:31
> I have a php form that sends an email based up user input inside my application

You have a PHP forum that generate and email and send it to the email monitored by the UVdesk Help Desk?

UVdesk never support ticket creation from a reply to email address, there is no workflow for this.
The issue on opening a ticket by a PHP form that generate email is that you cannot use the customer email address as sender or this will be a not authenticated email.

I have a live chat on my website, I want open a ticket when customer leave an offline message in the live chat.
This is currently not possible with UVdesk but was with OsTicket because the PHP form send an email  with mine authenticated email address and inserted the customer email as reply to address than, a workflow like: when email from is email@mydomain.ext use the reply to email address.

I think it's a problem open a ticket from external forms that are not UVdesk.
Something that can help in the future is support, as OsTicket, a workflow to use the reply to email address to open a ticket in some particular workflow where admin set a rule: when email is from this email address use the reply to email address.

The form should insert the customer email in the reply to.
UVdesk currently never support this.

**Comment by steveb85** [comment] 2022-02-25 14:13
@PeopleInside  I think you’ve nailed it on the head! Thanks for your explaination! so you run two ticketing systems at the same time? or are you just trying out OsTicket? We’ve worked hard on all our help system, and apart from this, and a lack of live chat we’re happy with UVdesk. Anyone at UvDesk able to comment on if this could be added?

**Comment by PeopleInside** [comment] 2022-02-25 14:18
Currently I decided to use only UVdesk.
In my case who send an offline message from the live chat will never open a ticket 

I'm not using OsTicket anymore at the moment.
I think I have already asked to UVdesk team to add the reply to function in workflow to use a reply to address when is present ... But this is not supported yet at the moment.

**Comment by steveb85** [comment] 2022-02-25 16:29
Thanks @PeopleInside . will sit and wait it out as well. In the meantime i’ll just trigger emails to me directly and submit tickets as needed. the old work around.

**Comment by steveb85** [comment] 2022-02-25 16:48
exactly! that’s the goal

**Comment by PeopleInside** [comment] 2022-02-25 16:51
I have the doubt this will be not implemented shortly and I don't know if will be.
I hope but don't believe this too much.
My issue is opened since long time.

You can see there: https://github.com/uvdesk/community-skeleton/issues/316

**Comment by steveb85** [comment] 2022-03-14 22:07
@PeopleInside I just re-wrote the php page so it uses the api, rather than creating an email, it’s more upfront work but solved this perfectly. and is working seamlessly.

**Comment by PeopleInside** [comment] 2022-03-14 22:22
I'm glad to read you resolved @steveb85 :)

**Comment by Komal-sharma-2712** [comment] 2022-06-17 12:40
We are closing this issue.
If you facing any issues you can reply to us on the same thread.

**Closed by Komal-sharma-2712** 2022-06-17 12:40 UTC
