### ISSUE TITLE
PHP Fatal error: Allowed memory size of XXXXXXXXXX bytes exhausted (tried to allocate XXXX bytes)

### ISSUE THREAD

**Issue by manukbt** [uvdesk/community-skeleton#679] opened 2023-07-13 11:41 UTC
Logs
----
10.0.1.254 - - [13/Jul/2023:11:19:14 +0000] "GET /_wdt/c49682 HTTP/1.1" 200 4942 "https://abc.com/en/xxx/tickets" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

10.0.1.254 - - [13/Jul/2023:11:19:15 +0000] "GET /en/xxx/tickets/xhr HTTP/1.1" 200 6359 "https://abc.com/en/xxx/tickets" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

Thu Jul 13 11:19:35.946755 2023] [php7:error] [pid 3225] [client 10.0.1.254:36678] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/symfony/property-access/PropertyAccessor.php on line 397
----
Thu Jul 13 11:19:35.947922 2023] [php7:error] [pid 3225] [client 10.0.1.254:36678] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1
----
old
memory_limit = 512M

new
memory_limit = 1G
before  "GET by ticket id method" was working fine but we add privileges  to agents " GET by ticket id method " is not working..?

**Comment by Komal-sharma-2712** [comment] 2023-07-13 12:26
@manukbt 

Can you please share a log file under your project follow the below path:
`your-project-folder-name/var/log/dev.log file`

![dev log-file](https://github.com/uvdesk/community-skeleton/assets/63539748/2870e04b-3f06-4910-ad07-c828aab1407b)


Also, you can check the error in the **dev.log** file. Open your **dev.log** file then search the "_uncaught_" exceptions.

**Comment by manukbt** [comment] 2023-07-14 05:25
[2023-07-14 05:18:51] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.created_at AS created_at_4, t0.is_active AS is_active_5 FROM uv_support_team t0 INNER JOIN uv_user_support_teams ON t0.id = uv_user_support_teams.supportTeamId WHERE uv_user_support_teams.userInstanceId = ? [38] []
[2023-07-14 05:18:51] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.created_at AS created_at_4, t0.is_active AS is_active_5, t0.user_view AS user_view_6 FROM uv_support_group t0 INNER JOIN uv_user_support_groups ON t0.id = uv_user_support_groups.supportGroupId WHERE uv_user_support_groups.userInstanceId = ? [38] []
[2023-07-14 05:18:51] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.created_at AS created_at_4, t0.is_active AS is_active_5 FROM uv_support_team t0 INNER JOIN uv_lead_support_teams ON t0.id = uv_lead_support_teams.supportTeamId WHERE uv_lead_support_teams.leadUserInstanceId = ? [38] []
[2023-07-14 05:18:51] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.created_at AS created_at_4, t0.is_active AS is_active_5, t0.user_view AS user_view_6 FROM uv_support_group t0 INNER JOIN uv_admin_support_groups ON t0.id = uv_admin_support_groups.supportGroupId WHERE uv_admin_support_groups.adminUserInstanceId = ? [38] []
[2023-07-14 05:18:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.path AS path_3, t0.content_type AS content_type_4, t0.size AS size_5, t0.content_id AS content_id_6, t0.file_system AS file_system_7, t0.thread_id AS thread_id_8 FROM uv_ticket_attachments t0 WHERE t0.thread_id = ? [79] []
[2023-07-14 05:18:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.stars AS stars_2, t0.feedback AS feedback_3, t0.created_at AS created_at_4, t0.ticket_id AS ticket_id_5, t0.user_id AS user_id_6 FROM uv_ticket_rating t0 WHERE t0.ticket_id = ? [70] []
[2023-07-14 05:18:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.proxy_id AS proxy_id_3, t0.password AS password_4, t0.first_name AS first_name_5, t0.last_name AS last_name_6, t0.is_enabled AS is_enabled_7, t0.verification_code AS verification_code_8, t0.timezone AS timezone_9, t0.timeformat AS timeformat_10 FROM uv_user t0 INNER JOIN uv_tickets_collaborators ON t0.id = uv_tickets_collaborators.user_id WHERE uv_tickets_collaborators.ticket_id = ? [70] []

[2023-07-14 05:19:08] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2 FROM uv_tag t0 INNER JOIN uv_tickets_tags ON t0.id = uv_tickets_tags.tag_id WHERE uv_tickets_tags.ticket_id = ? [70] []

[2023-07-14 05:19:08] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.color_code AS color_code_3, t0.user_id AS user_id_4 FROM uv_support_label t0 INNER JOIN uv_tickets_labels ON t0.id = uv_tickets_labels.label_id WHERE uv_tickets_labels.ticket_id = ? [70] []

[2023-07-14 05:19:09] php.CRITICAL: Fatal Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 199233536 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 199233536 bytes) at /var/www/html/vendor/symfony/serializer/Encoder/JsonEncode.php:53)"} []
-----
*dev.log* file error, "There are no 'uncaught' exceptions in the last request of the dev.log file.
 postman status : 500 Internal Server Error

**Comment by manukbt** [comment] 2023-07-18 17:43
@Komal-sharma-2712
waiting for replay...

**Comment by Komal-sharma-2712** [comment] 2023-10-19 10:01
We are not able to reproduce this issue. Can you please share a screen video for this issue.
At this moment, we are closing this issue. You can reply on the same thread.

Thanks and Regards,
Uvdesk Team

**Closed by Komal-sharma-2712** 2023-10-19 10:01 UTC
